/**
 * [389] Find the Difference
 *
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *  
 * Example 1:
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * Example 2:
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 * Example 3:
 * 
 * Input: s = "a", t = "aa"
 * Output: "a"
 * 
 * Example 4:
 * 
 * Input: s = "ae", t = "aea"
 * Output: "a"
 * 
 *  
 * Constraints:
 * 
 * 	0 <= s.length <= 1000
 * 	t.length == s.length + 1
 * 	s and t consist of lower-case English letters.
 * 
 */
pub struct Solution {}

// problem: https://leetcode.com/problems/find-the-difference/
// discuss: https://leetcode.com/problems/find-the-difference/discuss/?currentPage=1&orderBy=most_votes&query=

// submission codes start here

impl Solution {
    pub fn find_the_difference(s: String, t: String) -> char {
        let l = s.chars().fold(0u8, |acc, c|{acc ^ (c as u8)});
        t.chars().fold(l, |acc, c|{acc ^ (c as u8)}) as char
    }
}

// submission codes end

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_389() {
    }
}
